package com.coupleapp.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

// Stores every notification generated by the app.
// Lets us show notification history and track read/unread state per user.
@Entity
@Table(name = "notifications")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Notification {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The user who should receive this notification
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "recipient_user_id", nullable = false)
    private User recipient;

    // The message shown in the push notification banner
    // Written in a human, couple-friendly tone — NOT corporate (e.g. "Hey! Dishes are still waiting 😬")
    @Column(nullable = false, length = 300)
    private String message;

    // What triggered this — lets the app navigate to the right screen when tapped
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private NotificationType type;

    // ID of the related entity (taskId, eventId, goalId) — used for deep-linking
    @Column(name = "reference_id")
    private Long referenceId;

    // Whether the user has opened/seen this notification
    @Column(nullable = false)
    @Builder.Default
    private Boolean read = false;

    // Scheduled delivery time — allows future nudges to be queued
    @Column(name = "scheduled_for")
    private LocalDateTime scheduledFor;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    public enum NotificationType {
        TASK_ASSIGNED,
        TASK_DUE_SOON,
        TASK_OVERDUE,
        TASK_COMPLETED,
        CALENDAR_REMINDER,
        ANNIVERSARY_REMINDER,
        COUPLE_INVITE,
        WISHLIST_UPDATE,
        FINANCE_ALERT,
        ACTIVITY_REMINDER,
        GOAL_MILESTONE  // e.g. "You're 50% of the way to your vacation fund!"
    }
}
